create database employee;
use employee;

-- Create tables and load data
-- emp_record_table
CREATE TABLE EMP_RECORD_TABLE (
	EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    GENDER CHAR(1),
    ROLE VARCHAR(50),
    DEPT VARCHAR(30),
    EXP INT,
    COUNTRY VARCHAR(30),
    CONTINENT VARCHAR(20),
    SALARY DECIMAL(10, 2),
    EMP_RATING INT,
    MANAGER_ID INT,
    PROJ_ID INT
);




-- Proj_table
CREATE TABLE PROJ_TABLE (
	PROJECT_ID		INT AUTO_INCREMENT PRIMARY KEY,
    PROJ_NAME		VARCHAR(100),
    DOMAIN			VARCHAR(30),
    START_DATE		DATE,
    CLOSURE_DATE	DATE,
    DEV_QTR			VARCHAR(2),
    STATUS			VARCHAR(15)
);
-- Data_science_team
CREATE TABLE DATA_SCIENCE_TEAM (
	EMP_ID		INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME 	VARCHAR(30),
    LAST_NAME 	VARCHAR(30),
    GENDER 		CHAR(1),
    ROLE 		VARCHAR(50),
    DEPT 		VARCHAR(30),
    EXP 		INT,
    COUNTRY 	VARCHAR(30),
    CONTINENT 	VARCHAR(20)
);