-- To get MYSQL Workbench to work with load data file:
-- SHOW GLOBAL VARIABLES LIKE 'local_infile';
-- SET GLOBAL local_infile = true;
-- RELAXES CHECK ON STORED FUNCTION => SET GLOBAL log_bin_trust_function_creators = 1;

drop database if exists employee;
create database employee;
use employee;

-- CLEANUP
DROP TABLE IF EXISTS DATA_SCIENCE_TEAM;
DROP TABLE IF EXISTS PROJ_EMP_TABLE;
DROP TABLE IF EXISTS EMP_RECORD_TABLE;
DROP TABLE IF EXISTS PROJ_TABLE;

-- 1. Create tables

-- Proj_table

CREATE TABLE PROJ_TABLE (
	ID				INT AUTO_INCREMENT PRIMARY KEY,
	PROJECT_ID		VARCHAR(5) UNIQUE NOT NULL,
    PROJ_NAME		VARCHAR(100)  NOT NULL,
    DOMAIN			VARCHAR(30)  NOT NULL,
    START_DATE		DATE,
    CLOSURE_DATE	DATE,
    DEV_QTR			VARCHAR(2),
    STATUS			VARCHAR(20)  NOT NULL
);

-- select * from PROJ_TABLE;

LOAD DATA LOCAL INFILE 'datasets/proj_table.csv'
INTO TABLE PROJ_TABLE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(PROJECT_ID,PROJ_NAME,DOMAIN,@START_DATE,@CLOSURE_DATE,DEV_QTR,STATUS)
SET CLOSURE_DATE=STR_TO_DATE(@CLOSURE_DATE, '%m/%d/%Y'),
START_DATE=COALESCE( STR_TO_DATE(@START_DATE, '%m-%d-%Y'), STR_TO_DATE(@START_DATE,'%m/%d/%Y'))
;

-- emp_record_table
CREATE TABLE EMP_RECORD_TABLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
	EMP_ID VARCHAR(10) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(30)  NOT NULL,
    LAST_NAME VARCHAR(30)  NOT NULL,
    GENDER CHAR(1)  NOT NULL,
    ROLE VARCHAR(50)  NOT NULL,
    DEPT VARCHAR(30),
    EXP INT  NOT NULL,
    COUNTRY VARCHAR(30)  NOT NULL,
    CONTINENT VARCHAR(20)  NOT NULL,
    SALARY DECIMAL(10, 2)  NOT NULL,
    EMP_RATING INT,
    MANAGER_ID VARCHAR(5),
    PROJ_ID VARCHAR(5)
);


LOAD DATA LOCAL INFILE 'datasets/emp_record_table.csv'
INTO TABLE EMP_RECORD_TABLE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(EMP_ID,FIRST_NAME,LAST_NAME,GENDER,ROLE,DEPT,EXP,COUNTRY,CONTINENT,SALARY,EMP_RATING,MANAGER_ID,PROJ_ID);

-- proj_emp_table

CREATE TABLE PROJ_EMP_TABLE (
	PROJ_ID VARCHAR(5) NOT NULL,
    EMP_ID VARCHAR(5) NOT NULL,
	FOREIGN KEY (PROJ_ID) REFERENCES PROJ_TABLE(PROJECT_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (EMP_ID) REFERENCES EMP_RECORD_TABLE(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY (PROJ_ID, EMP_ID)
);
-- populate this table from existing data

INSERT INTO PROJ_EMP_TABLE (PROJ_ID, EMP_ID)
SELECT p.PROJECT_ID, e.EMP_ID FROM PROJ_TABLE p
LEFT JOIN  EMP_RECORD_TABLE e ON p.PROJECT_ID=e.PROJ_ID;

SELECT * FROM PROJ_EMP_TABLE;
-- Data_science_team
CREATE TABLE DATA_SCIENCE_TEAM (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID		VARCHAR(5) UNIQUE NOT NULL,
    FIRST_NAME 	VARCHAR(30)  NOT NULL,
    LAST_NAME 	VARCHAR(30)  NOT NULL,
    GENDER 		CHAR(1)  NOT NULL,
    ROLE 		VARCHAR(50)  NOT NULL,
    DEPT 		VARCHAR(30),
    EXP 		INT  NOT NULL,
    COUNTRY 	VARCHAR(30) NOT NULL,
    CONTINENT 	VARCHAR(20)  NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMP_RECORD_TABLE(EMP_ID)
);

LOAD DATA LOCAL INFILE 'datasets/data_science_team.csv'
INTO TABLE DATA_SCIENCE_TEAM
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(EMP_ID,FIRST_NAME,LAST_NAME,GENDER,ROLE,DEPT,EXP,COUNTRY,CONTINENT);

-- normalize DATA_SCIENCE_TEAM
ALTER TABLE DATA_SCIENCE_TEAM 
DROP COLUMN FIRST_NAME,
DROP COLUMN LAST_NAME,
DROP COLUMN GENDER,
DROP COLUMN ROLE,
DROP COLUMN DEPT,
DROP COLUMN EXP,
DROP COLUMN COUNTRY,
DROP COLUMN CONTINENT;
