-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 22:58:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema employee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employee` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `employee` ;

-- -----------------------------------------------------
-- Table `employee`.`EMP_RECORD_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`EMP_RECORD_TABLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMP_ID` VARCHAR(10) NOT NULL,
  `FIRST_NAME` VARCHAR(30) NOT NULL,
  `LAST_NAME` VARCHAR(30) NOT NULL,
  `GENDER` CHAR(1) NOT NULL,
  `ROLE` VARCHAR(50) NOT NULL,
  `DEPT` VARCHAR(30) NULL DEFAULT NULL,
  `EXP` INT NOT NULL,
  `COUNTRY` VARCHAR(30) NOT NULL,
  `CONTINENT` VARCHAR(20) NOT NULL,
  `SALARY` DECIMAL(10,2) NOT NULL,
  `EMP_RATING` INT NULL DEFAULT NULL,
  `MANAGER_ID` VARCHAR(5) NULL DEFAULT NULL,
  `PROJ_ID` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMP_ID` (`EMP_ID` ASC) VISIBLE,
  INDEX `FIRST_NAME_INDX` (`FIRST_NAME` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`DATA_SCIENCE_TEAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`DATA_SCIENCE_TEAM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMP_ID` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMP_ID` (`EMP_ID` ASC) VISIBLE,
  CONSTRAINT `data_science_team_ibfk_1`
    FOREIGN KEY (`EMP_ID`)
    REFERENCES `employee`.`EMP_RECORD_TABLE` (`EMP_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`PROJ_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`PROJ_TABLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` VARCHAR(5) NOT NULL,
  `PROJ_NAME` VARCHAR(100) NOT NULL,
  `DOMAIN` VARCHAR(30) NOT NULL,
  `START_DATE` DATE NULL DEFAULT NULL,
  `CLOSURE_DATE` DATE NULL DEFAULT NULL,
  `DEV_QTR` VARCHAR(2) NULL DEFAULT NULL,
  `STATUS` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PROJECT_ID` (`PROJECT_ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee`.`PROJ_EMP_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`PROJ_EMP_TABLE` (
  `PROJ_ID` VARCHAR(5) NOT NULL,
  `EMP_ID` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`PROJ_ID`, `EMP_ID`),
  INDEX `EMP_ID` (`EMP_ID` ASC) VISIBLE,
  CONSTRAINT `proj_emp_table_ibfk_1`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `employee`.`PROJ_TABLE` (`PROJECT_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `proj_emp_table_ibfk_2`
    FOREIGN KEY (`EMP_ID`)
    REFERENCES `employee`.`EMP_RECORD_TABLE` (`EMP_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `employee` ;

-- -----------------------------------------------------
-- Placeholder table for view `employee`.`sal_over_6k_emp_vw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee`.`sal_over_6k_emp_vw` (`ID` INT, `EMP_ID` INT, `FIRST_NAME` INT, `LAST_NAME` INT, `GENDER` INT, `ROLE` INT, `DEPT` INT, `EXP` INT, `COUNTRY` INT, `CONTINENT` INT, `SALARY` INT, `EMP_RATING` INT, `MANAGER_ID` INT, `PROJ_ID` INT);

-- -----------------------------------------------------
-- function RoleExpCheck
-- -----------------------------------------------------

DELIMITER $$
USE `employee`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `RoleExpCheck`(eid varchar(5)) RETURNS int
BEGIN
	DECLARE ROLED VARCHAR(50);
    DECLARE EXPD INT;
	SELECT ROLE INTO ROLED FROM EMP_RECORD_TABLE WHERE EMP_ID = EID;
    SELECT EXP INTO EXPD FROM EMP_RECORD_TABLE WHERE EMP_ID = EID;
    
	CASE ROLED
		WHEN 'JUNIOR DATA SCIENTIST' THEN RETURN IF( EXPD <=2 , 1, 0);
		WHEN 'ASSOCIATE DATA SCIENTIST' THEN RETURN IF( EXPD BETWEEN 2 AND 5, 1, 0);
        WHEN 'SENIOR DATA SCIENTIST' THEN RETURN IF (EXPD BETWEEN 5 AND 10, 1, 0);
        WHEN 'LEAD DATA SCIENTIST' THEN RETURN IF (EXPD BETWEEN 10 AND 12, 1, 0);
        WHEN 'MANAGER' THEN RETURN IF (EXPD BETWEEN 12 AND 16, 1, 0);
		ELSE
			RETURN -1;
	END CASE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure getEmpExpOver3
-- -----------------------------------------------------

DELIMITER $$
USE `employee`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getEmpExpOver3`()
BEGIN
	SELECT * FROM EMP_RECORD_TABLE WHERE EXP > 3;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `employee`.`sal_over_6k_emp_vw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee`.`sal_over_6k_emp_vw`;
USE `employee`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `employee`.`sal_over_6k_emp_vw` AS select `employee`.`emp_record_table`.`ID` AS `ID`,`employee`.`emp_record_table`.`EMP_ID` AS `EMP_ID`,`employee`.`emp_record_table`.`FIRST_NAME` AS `FIRST_NAME`,`employee`.`emp_record_table`.`LAST_NAME` AS `LAST_NAME`,`employee`.`emp_record_table`.`GENDER` AS `GENDER`,`employee`.`emp_record_table`.`ROLE` AS `ROLE`,`employee`.`emp_record_table`.`DEPT` AS `DEPT`,`employee`.`emp_record_table`.`EXP` AS `EXP`,`employee`.`emp_record_table`.`COUNTRY` AS `COUNTRY`,`employee`.`emp_record_table`.`CONTINENT` AS `CONTINENT`,`employee`.`emp_record_table`.`SALARY` AS `SALARY`,`employee`.`emp_record_table`.`EMP_RATING` AS `EMP_RATING`,`employee`.`emp_record_table`.`MANAGER_ID` AS `MANAGER_ID`,`employee`.`emp_record_table`.`PROJ_ID` AS `PROJ_ID` from `employee`.`emp_record_table` where (`employee`.`emp_record_table`.`SALARY` > 6000);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
